version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: math_learning_api
    restart: unless-stopped
    environment:
      FLASK_ENV: development
      CORS_ORIGINS: "*"
      REPLICATE_API_TOKEN: "${REPLICATE_API_TOKEN}"
      MONGODB_URI: "${MONGODB_URI}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
    ports:
      - "5050:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5050
    container_name: math_learning_web
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5050
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
